print('You will be'+str(int(my age)+1)+'in a year')
print('You will be'+str(int('4')+1)+'in a year')
print('You will be'+str(4+1)+'in a year')
print('You will be'+str(5)+'in a year')
print('You will be'+'5'+'in a year')
print('You will be 5'+'in a year')
print('You will be 5 in a year')